### ISSUE TITLE
Issue with zoom?

### ISSUE THREAD

**Issue by Iapetus-11** [maxheyn/hackman#2]
- At default zoom it zooms in wayyyy too much
- At 80% zoom it seems to work fine but some of the screen might be cut off
![image](https://user-images.githubusercontent.com/38477514/154308516-5f8b6dd4-8323-41ad-bdae-9ea3b1e7c402.png)
![image](https://user-images.githubusercontent.com/38477514/154308561-759fee86-6579-4a79-8a9f-3b7b7755ccc3.png)
- Anything less than 80% zoom makes the game really tiny
![image](https://user-images.githubusercontent.com/38477514/154308701-d7726d3b-653b-4f7a-8ad5-e290998de540.png)

**Comment by maxheyn** [comment]
Should be fixed in ed0751d353d1f04c3f6678a147d87387bf631455
